"""Added measure table

Revision ID: 223409afd403
Revises: 53d9f3f561a8
Create Date: 2022-11-26 23:36:52.100221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '223409afd403'
down_revision = '53d9f3f561a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measure',
    sa.Column('uuid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_measure_uuid'), 'measure', ['uuid'], unique=False)
    op.add_column('ingredient', sa.Column('uuid_measure', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ingredient', 'measure', ['uuid_measure'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingredient', type_='foreignkey')
    op.drop_column('ingredient', 'uuid_measure')
    op.drop_index(op.f('ix_measure_uuid'), table_name='measure')
    op.drop_table('measure')
    # ### end Alembic commands ###
