"""added file table and relationship with recipe

Revision ID: 5335dc26cb31
Revises: 61b16075cd6a
Create Date: 2022-12-17 16:21:46.539303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5335dc26cb31'
down_revision = '61b16075cd6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('uuid', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('image_preview', 'image_other', 'document', name='filetype'), nullable=True),
    sa.Column('uuid_recipe', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uuid_recipe'], ['recipe.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_file_uuid'), 'file', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_uuid'), table_name='file')
    op.drop_table('file')
    # ### end Alembic commands ###
