"""Added cascade

Revision ID: 61b16075cd6a
Revises: 223409afd403
Create Date: 2022-12-02 01:43:53.975638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61b16075cd6a'
down_revision = '223409afd403'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('consistency_ingredient_uuid_layer_fkey', 'consistency_ingredient', type_='foreignkey')
    op.create_foreign_key(None, 'consistency_ingredient', 'layer', ['uuid_layer'], ['uuid'], ondelete='CASCADE')
    op.drop_constraint('layer_uuid_recipe_fkey', 'layer', type_='foreignkey')
    op.create_foreign_key(None, 'layer', 'recipe', ['uuid_recipe'], ['uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'layer', type_='foreignkey')
    op.create_foreign_key('layer_uuid_recipe_fkey', 'layer', 'recipe', ['uuid_recipe'], ['uuid'])
    op.drop_constraint(None, 'consistency_ingredient', type_='foreignkey')
    op.create_foreign_key('consistency_ingredient_uuid_layer_fkey', 'consistency_ingredient', 'layer', ['uuid_layer'], ['uuid'])
    # ### end Alembic commands ###
